Repository ArkEcosystem/exchange-json-rpc, pull requests merged in 2019-05, with the labels that each got.

#2 chore: add badges to README
  README.md
Labels: Complexity: Low, Type: Task

#3 chore: add github templates
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Documentation_issue.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Security_vulnerabilities.md
  .github/ISSUE_TEMPLATE/Support_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#4 chore: remove core release section from PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Complexity: Low, Type: Task

#5 chore(deps): remove unused dependencies
  package.json
  tslint-config.json
  yarn.lock
Labels: Complexity: High, Type: Task

#7 feat: use average fee on the network as transaction fee
  src/server/index.ts
  src/server/methods.ts
  src/server/utils.ts
Labels: Complexity: Medium, Type: Feature

#11 refactor: update @hapist/json-rpc and use custom validator
  package.json
  src/cli/commands/status.ts
  src/server/index.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#12 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#10 refactor: use blockId schema
  __tests__/blocks.test.ts
  __tests__/wallets.test.ts
  src/server/index.ts
  src/server/methods.ts
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#13 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Documentation_issue.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Security_vulnerabilities.md
  .github/ISSUE_TEMPLATE/Support_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#14 build: sequentially build modules with yarn
  .yarnrc
  package.json
  yarn.lock
Labels: Complexity: High

#15 refactor: replace keyv with better-sqlite3 to support node.js 12
  .circleci/config.yml
  __tests__/__support__/index.ts
  __tests__/server/blocks.test.ts
  __tests__/server/transactions.test.ts
  __tests__/server/wallets.test.ts
  __tests__/services/database.test.ts
  package.json
  src/cli/commands/run.ts
  src/services/database.ts
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Refactor

#16 refactor: break up RPC and CLI
  .lintstagedrc.json
  lerna.json
  package.json
  packages/cli/CHANGELOG.md
  packages/cli/bin/run
  packages/cli/bin/run.cmd
  packages/cli/package.json
  packages/cli/src/commands/command.ts
  packages/cli/src/commands/log.ts
  packages/cli/src/commands/restart.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/status.ts
  packages/cli/src/commands/stop.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/helpers/prompts.ts
  packages/cli/src/helpers/update.ts
  packages/cli/src/hooks/command_not_found/suggest.ts
  packages/cli/src/hooks/init/update.ts
  packages/cli/src/index.ts
  packages/cli/src/process-manager.ts
  packages/cli/src/types.ts
  packages/cli/src/utils.ts
  packages/cli/tsconfig.json
  packages/rpc/CHANGELOG.md
  packages/rpc/__tests__/__support__/index.ts
  packages/rpc/__tests__/server/blocks.test.ts
  packages/rpc/__tests__/server/transactions.test.ts
  packages/rpc/__tests__/server/wallets.test.ts
  packages/rpc/__tests__/services/database.test.ts
  packages/rpc/package.json
  packages/rpc/src/index.ts
  packages/rpc/src/interfaces.ts
  packages/rpc/src/server/index.ts
  packages/rpc/src/server/methods.ts
  packages/rpc/src/server/utils.ts
  packages/rpc/src/services/database.ts
  packages/rpc/src/services/logger.ts
  packages/rpc/src/services/network.ts
  packages/rpc/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress, Type: Refactor
