Repository ArkEcosystem/exchange-json-rpc, pull requests merged in 2019-11, with the labels that each got.

#54 test: fix failing and update workflow
  .github/workflows/test.yml
  packages/rpc/__tests__/server/wallets.test.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Test: Unit

#52 feat: add nonce support for Core 2.6
  packages/rpc/package.json
  packages/rpc/src/server/methods.ts
  packages/rpc/src/server/utils.ts
  packages/rpc/src/services/network.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#53 feat: peer discovery using @arkecosystem/peers
  README.md
  packages/cli/package.json
  packages/cli/src/commands/command.ts
  packages/rpc/src/server/index.ts
  packages/rpc/src/services/network.ts
  yarn.lock
Labels: Bounty: Tier 1, Complexity: Medium, Status: Needs Review, Type: Feature
