Repository ArkEcosystem/exchange-json-rpc, pull requests merged in 2020-02, with the labels that each got.

#81 feat: vote and delegate registration creation
  packages/rpc/__tests__/server/transactions.test.ts
  packages/rpc/src/server/methods.ts
  packages/rpc/src/server/utils.ts
  packages/rpc/src/utils/crypto.ts
  packages/rpc/src/utils/transactions.ts
Labels: Complexity: High, Type: Feature

#82 feat: pre aip11 compatibility
  packages/rpc/__tests__/server/transactions.test.ts
  packages/rpc/src/services/network.ts
  packages/rpc/src/utils/transactions.ts
Labels: Complexity: Medium, Type: Feature

#84 release: 2.0.0
  lerna.json
  packages/cli/package.json
  packages/rpc/package.json
Labels: Complexity: Low, Type: Release
